Improve bin/run_app script
- Allow for either running in dev or prod (with Gunicorn)
- Add usage/help option to script
- Update Dockerfile, Makefile, and Procfile based on changes
- Update deploy rule based on changes to bin/run_app

diff --git a/bin/run_app b/bin/run_app
--- a/bin/run_app
+++ b/bin/run_app
@@ -1,7 +1,60 @@
 #!/bin/bash
 
-export FLASK_APP=app/app.py
-export FLASK_ENV=development
+set -eu
 
-HOST=${1:-127.0.0.1}
-python -m flask run --host=$HOST
+usage() {
+    echo "Usage: $0 [-h] [-o HOST] CONFIG"
+    echo -e "Run Flask application in either development or production configuration\n"
+    echo "Required arguments:"
+    echo -e "CONFIG \t Configuration of the application, either dev or prod\n"
+    echo "Options:"
+    echo -e "-h \t Show this help message and exit"
+    echo -e "-o \t The interface to bind to, the host"
+}
+
+parse_option() {
+    while getopts "o:h" option; do
+	case "$option" in
+	    o)
+	      HOST="$OPTARG";;
+	    h)
+		usage
+		exit 0;;
+	    \?)
+		usage 1>&2
+		exit 1;;
+	esac
+    done
+
+    shift "$(($OPTIND -1))"
+
+    HOST=${HOST:-127.0.0.1}
+    ARGS="$@"
+}
+
+parse_config() {
+    if [[ ("$1" == "dev") || ("$1" == "prod") ]]; then
+	CONFIG="$1"
+    else
+	echo "Illegal required positional argument: $1"
+	usage
+	exit 1
+    fi
+}
+
+run_app() {
+    if [[ "$CONFIG" == "dev" ]]; then
+	FLASK_ENV=development flask run --host "$HOST"
+    elif [[ "$CONFIG" == "prod" ]]; then
+	gunicorn "wsgi:create_app('prod')"
+    fi
+}
+
+main() {
+    parse_option "$@"
+    parse_config "$ARGS"
+    run_app
+}
+
+
+main "$@"
